name: Security Scans

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ] 
    
jobs: 

  build-and-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build application
        run: |
          npm install
          # This has a postinstall job that runs the build for the frontend and server

      - name: Install Semgrep
        run: python3 -m pip install semgrep

      - name: Semgrep SAST Scan
        run: semgrep ci --config "p/nodejs" --sarif --output semgrep-results.sarif --timeout 0
        continue-on-error: true

      - name: Upload SAST Results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-results.sarif
          category: semgrep

      
