name: Security Scans

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ] 
    
jobs: 

  build-and-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        
