name: Security Scans

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ] 
    
jobs: 

  build-and-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: "Build application"
        run: |
          npm install
          # This has a postinstall job that runs the build for the frontend and server

      - name: "Semgrep SAST Scan"
        uses: semgrep/semgrep-action@v1
      
